variables:
    RUST_BACKTRACE: "FULL"

stages:
  - test
  - build
  - release

test_latest:
    stage: test
    image: "rust:latest"
    script:
      - rustc --version && cargo --version
      - cargo build
      - cargo test --all --verbose

test_nightly:
    stage: test
    image: rustlang/rust:nightly
    script:
      - rustc --version && cargo --version
      - cargo build
      - cargo test --all --verbose
    allow_failure: true

build_linux_job:
  stage: build
  image: "rust:latest"
  artifacts:
    paths:
      - target/release/linkchecker
  script:
    - cargo build --verbose --release

build_debian_job:
  stage: build
  image: "rust:latest"
  artifacts:
    paths:
      - target/debian
  script:
    - cargo install cargo-deb
    - cargo deb
  only:
    - tags

release_job:
  stage: release
  image: python:3.7-slim
  script:
    - pip3 install gitlab-release
    - gitlab-release target/debian/*.deb
  only:
    - tags