image: "rust:latest"

variables:
    RUST_BACKTRACE: "FULL"

stages:
  - build
  - release

build_osx:
  image: joseluisq/rust-linux-darwin-builder:latest
  stage: build
  artifacts:
    paths:
      - /builds/becheran/mlc_ci
  script:
    - cargo build --release --target x86_64-apple-darwin

build_linux:
  stage: build
  artifacts:
    paths:
      - target/release/mlc
  script:
    - cargo build --verbose --release  

test_latest:
    stage: build
    script:
      - cargo test --all --verbose

test_nightly:
    stage: build
    image: rustlang/rust:nightly
    script:
      - cargo test --all --verbose
    allow_failure: true

release_github_artifact:
  stage: release
  image: golang:latest
  script:
    - go get github.com/aktau/github-release
    - github-release release --user becheran --repo mlc --tag $CI_COMMIT_TAG
    - github-release upload --user becheran --repo mlc --tag $CI_COMMIT_TAG --name "mlc-x86_64-linux" --file target/release/mlc
    - github-release upload --user becheran --repo mlc --tag $CI_COMMIT_TAG --name "mlc-x86_64-apple-darwin" --file /builds/becheran/mlc_ci
    /builds/becheran/mlc_ci
  only:
    - tags

release_docker:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t becheran/mlc .
    - version="${CI_COMMIT_TAG:1}"
    - docker tag becheran/mlc becheran/mlc:$version
    - docker push becheran/mlc
  only:
    - tags
