image: "rust:latest"

variables:
    RUST_BACKTRACE: "FULL"

stages:
  - test
  - build
  - release

test_job:
    stage: test
    script:
      - rustc --version && cargo --version
      - cargo build
      - cargo test --all --verbose

build_linux_job:
  stage: build
  artifacts:
    paths:
      - target/release/linkchecker
  script:
    - cargo build --verbose --release

release_debian_job:
  stage: release
  artifacts:
    paths:
      - target/debian
  script:
    - cargo install cargo-deb
    - cargo deb
  only:
    - tags