image: "rust:latest"

variables:
    RUST_BACKTRACE: "FULL"

stages:
  - test
  - build

test_job:
    stage: test
    script:
      - rustc --version && cargo --version
      - cargo build
      - cargo test --all --verbose

build_linux_job:
  stage: build
  artifacts:
    paths:
      - target/release/linkchecker
  script:
    - cargo build --verbose --release