variables:
    RUST_BACKTRACE: "FULL"

stages:
  - build
  - test
  - release

build_linux:
  stage: build
  image: "rust:latest"
  artifacts:
    paths:
      - target/release/mlc
  script:
    - cargo build --verbose --release  

test_latest:
    stage: test
    image: "rust:latest"
    script:
      - cargo test --all --verbose

test_nightly:
    stage: test
    image: rustlang/rust:nightly
    script:
      - cargo test --all --verbose
    allow_failure: true

release_job:
  stage: release
  image: python:3.7-slim
  script:
    - pip3 install gitlab-release==3.5
    - gitlab-release target/release/*
  only:
    - tags