image: "rust:latest"

variables:
    RUST_BACKTRACE: "FULL"

stages:
  - build
  - release

build_linux:
  stage: build
  artifacts:
    paths:
      - target/release/mlc
  script:
    - cargo build --verbose --release  

test_latest:
    stage: build
    script:
      - cargo test --all --verbose

test_nightly:
    stage: build
    image: rustlang/rust:nightly
    script:
      - cargo test --all --verbose
    allow_failure: true

release_job:
  stage: release
  image: golang:latest
  script:
    - go get github.com/aktau/github-release
    - github-release upload \
        --user becheran \
        --repo mlc \
        --tag $CI_COMMIT_TAG \
        --name "mlc" \
        --file target/release/mlc
  #only:
  #  - tags