variables:
    RUST_BACKTRACE: "FULL"

stages:
  - build
  - test
  - release

build_linux:
  stage: build
  image: "rust:latest"
  artifacts:
    paths:
      - target/release/mlc
  script:
    - cargo build --verbose --release  

test_latest:
    stage: test
    image: "rust:latest"
    script:
      - cargo test --all --verbose

test_nightly:
    stage: test
    image: rustlang/rust:nightly
    script:
      - cargo test --all --verbose
    allow_failure: true

release_job:
  stage: release
  image: golang:latest
  script:
    - go get github.com/aktau/github-release
    - github-release info -u becheran -r mlc
    #- github-release target/release/*
  #only:
  #  - tags