variables:
    RUST_BACKTRACE: "FULL"

stages:
  - test
  - release

test_latest:
    stage: test
    image: "rust:latest"
    script:
      - cargo test --all --verbose

test_nightly:
    stage: test
    image: rustlang/rust:nightly
    script:
      - cargo test --all --verbose
    allow_failure: true

release_job:
  stage: release
  image: python:3.7-slim
  script:
    - pip3 install gitlab-release==3.5
    - cargo build --release --verbose
    - gitlab-release target/release/*
  only:
    - tags