[package]
name = "linkchecker"
version = "0.1.0"
authors = ["Armin Becher <becherarmin@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.33", features = ["yaml"]}
log = "0.4.7"
simplelog = "0.6.0"
walkdir = "2"


