[package]
name = "mlc"
version = "0.2.0"
authors = ["Armin Becher <becherarmin@gmail.com>"]
edition = "2018"
description = "The markup link checker (mlc) checks for broken links in markup files."
keywords = [ "link", "checker", "markup", "markdown"]
readme = "README.md"
license = "MIT"

[package.metadata.deb]
maintainer = "Armin Becher <becherarmin@gmail.com>"

[dependencies]
clap = {version = "2.33.0", features = ["yaml"]}
log = "0.4.8"
simplelog = "0.7.4"
walkdir = "2.2.9"
regex = "1.3.1"
lazy_static = "1.4.0"
url = "2.1.0"
colored = "1.9.0"
reqwest = {version="0.9.24", features = ["default-tls-vendored"] }

[dev-dependencies]
ntest = "0.3.3"
criterion = "0.3.0"

[[bench]]
name = "benchmarks"
harness = false
