[package]
name = "linkchecker"
version = "0.1.0"
authors = ["Armin Becher <becherarmin@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.33", features = ["yaml"]}
log = "0.4"
simplelog = "0.7.3"
walkdir = "2"
regex = "1.3.1"
lazy_static = "1.4.0"
url = "2.1.0"

[dev-dependencies]
ntest = "0.2.1"