[package]
name = "mlc"
version = "0.8.1-alpha.0"
authors = ["Armin Becher <becherarmin@gmail.com>"]
edition = "2018"
description = "The markup link checker (mlc) checks for broken links in markup files."
keywords = [ "link-checker", "broken", "markup", "html", "markdown"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/becheran/mlc"

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-open-issues = { repository = "becheran/mlc" }
is-it-maintained-issue-resolution = { repository = "becheran/mlc" }

[dependencies]
clap = {version = "2.33.0", features = ["yaml"]}
log = "0.4.8"
simplelog = "0.7.4"
walkdir = "2.3.1"
regex = "1.3.3"
lazy_static = "1.4.0"
url = "2.1.1"
colored = "1.9.2"
reqwest = {version="0.10.1", features = ["native-tls-vendored"] }
tokio = {version="0.2.9", features = ["full"] } #TODO remove unused features
futures = "0.3.1"
wildmatch = "1.0.3"

[dev-dependencies]
ntest = "0.5.1"
criterion = "0.3.0"

[[bench]]
name = "benchmarks"
harness = false
